/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.uga.iut2.genconf.vue;

import fr.uga.iut2.genconf.modele.Utilisateur;
import javax.swing.DefaultListModel;
import java.util.Map;

/**
 *
 * @author linam
 */
public class VueAfficherUtilisateurs extends javax.swing.JPanel {

    private final GUI gui;
    /**
     * Creates new form VueAfficherUtilisateurs
     * @param gui
     * @param administrateurs
     * @param utilisateurs
     */
    public VueAfficherUtilisateurs(GUI gui, Map<String, Utilisateur> administrateurs, Map<String, Utilisateur> utilisateurs) {
    
        this.gui = gui;
        
        // création de l'interface générée
        this.initComponents();
        
        updateView(gui,administrateurs,utilisateurs);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listeAdmin = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        listeNonAdmin = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();

        jLabel1.setText("Liste des utilisateurs");

        jLabel4.setText("Administrateurs");

        jLabel5.setText("Utilisateurs non admin");

        listeAdmin.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listeAdmin);

        listeNonAdmin.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(listeNonAdmin);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    public final void updateView(GUI gui, Map<String, Utilisateur> administrateurs, Map<String, Utilisateur> utilisateurs){
        
        listeAdmin.removeAll();
        listeNonAdmin.removeAll();
        
        //on récupère la liste des administrateurs
        DefaultListModel listModelAdmin = new DefaultListModel<Utilisateur>();
        DefaultListModel listModelUtilisateur = new DefaultListModel<Utilisateur>();
        
        //verifier si la liste des admin est vide, si non vide alors on ajoute les admin un par un
        if(administrateurs.isEmpty() && utilisateurs.isEmpty()){
            listModelAdmin.addElement("Aucun Administrateur");
            listModelUtilisateur.addElement("Aucun Utilisateur");
        }else{
            for (Map.Entry<String, Utilisateur> admin : administrateurs.entrySet()) {
                listModelAdmin.addElement(admin.getValue().getEmail() + " (" + admin.getKey() + ")");
            }
        
            //on récupère la liste des utilisateurs non admin
            for (Map.Entry<String, Utilisateur> user : utilisateurs.entrySet()) {
                boolean isAdmin = false;
                for (Map.Entry<String, Utilisateur> admin : administrateurs.entrySet()){
                    if(user.getKey().equals(admin.getValue().getEmail())){
                        isAdmin = true;
                        break;
                    }
                }
                if (!isAdmin) {
                    listModelUtilisateur.addElement(user.getKey() + " (" + user.getValue().getNom() + " " + user.getValue().getPrenom() + ")");
                }
            }
        }
        listeAdmin.setModel(listModelAdmin);
        listeNonAdmin.setModel(listModelUtilisateur);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList<String> listeAdmin;
    private javax.swing.JList<String> listeNonAdmin;
    // End of variables declaration//GEN-END:variables
    }
