/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.uga.iut2.genconf.vue;

import fr.uga.iut2.genconf.modele.Session;
import fr.uga.iut2.genconf.modele.Utilisateur;
import java.awt.Color;
import java.util.Map;
import java.util.Optional;
import org.apache.commons.validator.routines.EmailValidator;
/**
 *
 * @author Adam
 */
public class VueCreationCommunication extends javax.swing.JPanel {
    
    
    private final GUI gui;
    private boolean valideComm;

    /**
     * Creates new form VueCreationCommunication
     * @param gui
     * @param sessions
     * @param orateurs
     */
    public VueCreationCommunication(GUI gui, Map<String,Session> sessions, Map<String, Utilisateur> orateurs) {
        this.gui = gui;
        this.valideComm = false;
        this.initComponents();
        
        updateView(gui,sessions);
        
        this.creer.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("checked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        titreComm = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mailC = new javax.swing.JTextField();
        creer = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        mailO = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nomSess = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Création d'une communication");

        jLabel2.setText("Titre :");

        titreComm.setText("titre de la communication");
        titreComm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verifierValider(evt);
            }
        });

        jLabel3.setText("e-mail du correspondant :");

        mailC.setText("e-mail du correspondant");
        mailC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verifierValider(evt);
            }
        });

        creer.setText("Créer");
        creer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreerActionCommunication(evt);
            }
        });

        jButton2.setText("Annuler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionCommunication(evt);
            }
        });

        jLabel5.setText("e-mail des orateurs :");

        mailO.setText("entrer l'e-mail d'un orateur ");
        mailO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verifierValider(evt);
            }
        });

        jButton3.setText("Ajouter");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionAjouterEmailO(evt);
            }
        });

        jLabel4.setText("Sélectionner une session :");

        nomSess.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(creer))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mailC, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mailO, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(titreComm, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nomSess, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nomSess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titreComm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mailC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(mailO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creer)
                    .addComponent(jButton2))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CreerActionCommunication(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreerActionCommunication
       IHM.InfosNouvelleCommunication nlleComm = new IHM.InfosNouvelleCommunication(
       this.nomSess.getSelectedItem().toString().trim(),
       this.titreComm.getText().trim(),
       this.mailC.getText(),
       this.mailO.getText()
       );
       
       this.gui.creerCommunication(Optional.of(nlleComm));
    }//GEN-LAST:event_CreerActionCommunication

    private void AnnulerActionCommunication(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionCommunication
        this.gui.creerCommunication(Optional.empty());
    }//GEN-LAST:event_AnnulerActionCommunication

    private void ActionAjouterEmailO(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionAjouterEmailO
        IHM.InfosNouveauOrateur nvOrateur = new IHM.InfosNouveauOrateur(
             this.nomSess.getSelectedItem().toString(),
             this.mailO.getText().trim()
        );
        
        mailO.setText("");
                
        this.gui.ajouterOrateur(Optional.of(nvOrateur));
    }//GEN-LAST:event_ActionAjouterEmailO

    private void verifierValider(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verifierValider
        boolean validEmailC, validEmailO;
        String nomSes, titreCo;
        EmailValidator validator = EmailValidator.getInstance(false, false);
        
        nomSes = this.nomSess.getSelectedItem().toString().trim();
        titreCo = this.titreComm.getText().trim();
        validEmailC = validator.isValid(this.mailC.getText().trim().toLowerCase());
        validEmailO = validator.isValid(this.mailO.getText().trim().toLowerCase());
        
        this.mailC.setForeground(validEmailC ? Color.black : Color.red);
        this.mailO.setForeground(validEmailO ? Color.black : Color.red);
        
       this.valideComm = validEmailC
               && (nomSes != null)
               && (titreCo != null) && (titreCo.length() > 0);
       
       this.creer.setEnabled(this.valideComm);
               
    }//GEN-LAST:event_verifierValider
    
    
    public final void updateView(GUI gui, Map<String,Session> sessions){
        nomSess.removeAllItems();
        
        if(sessions.isEmpty()){
            this.nomSess.addItem("Aucune Session");
            this.nomSess.setEnabled(false);
        }else{
            for(Map.Entry<String,Session> sess : sessions.entrySet()){
                this.nomSess.addItem(sess.getKey());
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton creer;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField mailC;
    private javax.swing.JTextField mailO;
    private javax.swing.JComboBox<String> nomSess;
    private javax.swing.JTextField titreComm;
    // End of variables declaration//GEN-END:variables
}
