package fr.uga.iut2.genconf.vue;

import java.awt.CardLayout;
import javax.swing.JPanel;


public class VuePrincipale extends javax.swing.JFrame {
    private final GUI gui;

    /**
     * Creates new form VuePrincipale
     */
    public VuePrincipale(GUI gui) {
        this.gui = gui;

        // création de l'interface générée
        this.initComponents();
    }

    protected void afficher() {
        this.setSize(600,400);
        this.setVisible(true);
    }

    protected void ajouterVue(JPanel vue, String id) {

        CardLayout cLayout = (CardLayout) this.getContentPane().getLayout();

        cLayout.addLayoutComponent(vue, id);
        this.add(vue);
    }

    protected void afficherVue(String id) {
        CardLayout cLayout = (CardLayout) getContentPane().getLayout();
        cLayout.show(this.getContentPane(), id);
        gui.updateViews();
    }

    protected void fermer() {
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GenConf");
        getContentPane().setLayout(new java.awt.CardLayout());

        jMenu1.setText("Gestion");

        jMenuItem1.setText("Créer une conférence");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuCreationConference(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Créer un utilisateur");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuCreationUtilisateur(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem11.setText("Créer une session");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuCreationSession(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        jMenuItem12.setText("Créer une communication");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuCreationCommunication(evt);
            }
        });
        jMenu1.add(jMenuItem12);

        jMenuItem5.setText("Donner droit administrateur");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuDonnerDroitAdministrateur(evt);
            }
        });
        jMenu1.add(jMenuItem5);
        jMenu1.add(jSeparator2);

        jMenuItem4.setText("Quitter");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuQuitter(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Affichage");

        jMenuItem6.setText("Afficher les utilisateurs");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuAfficherUtilisateurs(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem10.setText("Consulter infos conférence");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuSelectionnerConference(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Suppression");

        jMenuItem7.setText("Supprimer un utilisateur");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuSupprimerUtilisateur(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Supprimer une conférence");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuSupprimerConference(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actionMenuCreationUtilisateur(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionMenuCreationUtilisateur
        this.gui.actionCreerUtilisateur();
    }//GEN-LAST:event_actionMenuCreationUtilisateur

    private void actionMenuCreationConference(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionMenuCreationConference
        this.gui.actionCreerConference();
    }//GEN-LAST:event_actionMenuCreationConference
      
    private void actionMenuQuitter(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionMenuQuitter
        this.gui.actionTerminer();
    }//GEN-LAST:event_actionMenuQuitter

    private void actionMenuDonnerDroitAdministrateur(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionMenuDonnerDroitAdministrateur
        this.gui.actionDonnerDroitAdmin();
    }//GEN-LAST:event_actionMenuDonnerDroitAdministrateur

    private void actionMenuAfficherUtilisateurs(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionMenuAfficherUtilisateurs
        this.gui.actionAfficherUtilisateurs();
    }//GEN-LAST:event_actionMenuAfficherUtilisateurs

    private void actionMenuSelectionnerConference(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionMenuSelectionnerConference
        this.gui.actionSelectionnerConference();
    }//GEN-LAST:event_actionMenuSelectionnerConference

    private void actionMenuSupprimerUtilisateur(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionMenuSupprimerUtilisateur
        this.gui.actionSupprimerUtilisateur();
    }//GEN-LAST:event_actionMenuSupprimerUtilisateur

    private void actionMenuSupprimerConference(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionMenuSupprimerConference
        this.gui.actionSupprimerConference();
    }//GEN-LAST:event_actionMenuSupprimerConference

    private void actionMenuCreationSession(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionMenuCreationSession
        this.gui.actionCreerSession();
    }//GEN-LAST:event_actionMenuCreationSession

    private void actionMenuCreationCommunication(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionMenuCreationCommunication
        this.gui.actionCreerCommunication();
    }//GEN-LAST:event_actionMenuCreationCommunication

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables

    
}
